SET BOOST_PYTHON_PATH=D:\boost
SET PYTHON_INCLUDE=D:\Python27\include
SET PYTHON_LIB=D:\Python27\libs\python27.lib
SET WXPYTHON_LIB=D:\wxPython\libs\python27.lib
SET CASROOT=D:\OpenCASCADE\opencascade-6.9.1
SET WXWIN=D:\wxWidgets
SET LIBAREAPATH=D:\GitHub\CNC\libarea
SET HEEKSCADPATH=D:\GitHub\CNC\heekscad
START devenv
