
copy /y "%HEEKSCNCSOURCEPATH%\post for installer.bat" "%HEEKSCNCPATH%\post.bat"
copy /y "%HEEKSCNCSOURCEPATH%\nc_read for installer.bat" "%HEEKSCNCPATH%\nc_read.bat"
copy /y "%HEEKSCNCSOURCEPATH%\backplot.py" "%HEEKSCNCPATH%\backplot.py"
copy /y "%HEEKSCNCSOURCEPATH%\area_funcs.py" "%HEEKSCNCPATH%\area_funcs.py"
copy /y "%HEEKSCNCSOURCEPATH%\kurve_funcs.py" "%HEEKSCNCPATH%\kurve_funcs.py"
copy /y "%HEEKSCNCSOURCEPATH%\area_funcs.py" "%HEEKSCNCPATH%\area_funcs.py"
copy /y "%HEEKSCNCSOURCEPATH%\ocl_funcs.py" "%HEEKSCNCPATH%\ocl_funcs.py"
copy /y "%HEEKSCNCSOURCEPATH%\depth_params.py" "%HEEKSCNCPATH%\depth_params.py"
copy /y "%HEEKSCNCSOURCEPATH%\*.tooltable" "%HEEKSCNCPATH%"
copy /y "%HEEKSCNCSOURCEPATH%\script_ops.xml" "%HEEKSCNCPATH%\script_ops.xml"
mkdir "%HEEKSCNCPATH%\nc"
copy /y "%HEEKSCNCSOURCEPATH%\nc\*.py" "%HEEKSCNCPATH%\nc"
copy /y "%HEEKSCNCSOURCEPATH%\nc\machines.xml" "%HEEKSCNCPATH%\nc\machines.xml"
mkdir "%HEEKSCNCPATH%\bitmaps"
copy /y "%HEEKSCNCSOURCEPATH%\bitmaps\*.png" "%HEEKSCNCPATH%\bitmaps"
mkdir "%HEEKSCNCPATH%\bitmaps\ctool"
copy /y "%HEEKSCNCSOURCEPATH%\bitmaps\ctool\*.png" "%HEEKSCNCPATH%\bitmaps\ctool"
mkdir "%HEEKSCNCPATH%\bitmaps\depthop"
copy /y "%HEEKSCNCSOURCEPATH%\bitmaps\depthop\*.png" "%HEEKSCNCPATH%\bitmaps\depthop"
mkdir "%HEEKSCNCPATH%\bitmaps\drilling"
copy /y "%HEEKSCNCSOURCEPATH%\bitmaps\drilling\*.png" "%HEEKSCNCPATH%\bitmaps\drilling"
mkdir "%HEEKSCNCPATH%\bitmaps\pattern"
copy /y "%HEEKSCNCSOURCEPATH%\bitmaps\pattern\*.png" "%HEEKSCNCPATH%\bitmaps\pattern"
mkdir "%HEEKSCNCPATH%\bitmaps\pocket"
copy /y "%HEEKSCNCSOURCEPATH%\bitmaps\pocket\*.png" "%HEEKSCNCPATH%\bitmaps\pocket"
mkdir "%HEEKSCNCPATH%\bitmaps\profile"
copy /y "%HEEKSCNCSOURCEPATH%\bitmaps\profile\*.png" "%HEEKSCNCPATH%\bitmaps\profile"
mkdir "%HEEKSCNCPATH%\bitmaps\surface"
copy /y "%HEEKSCNCSOURCEPATH%\bitmaps\surface\*.png" "%HEEKSCNCPATH%\bitmaps\surface"
mkdir "%HEEKSCNCPATH%\icons"
copy /y "%HEEKSCNCSOURCEPATH%\icons\*.png" "%HEEKSCNCPATH%\icons"
copy /y "%HEEKSCNCSOURCEPATH%\Toolpath.py" "%HEEKSCNCPATH%\Toolpath.py"

rem copy all the voxelcut files into the same place as HeeksCNC, to re-use some of the files
copy /y "%VOXELCUTPATH%\voxelcut.bat" "%HEEKSCNCPATH%\voxelcut.bat"
copy /y "%VOXELCUTPATH%\*.py" "%HEEKSCNCPATH%"
copy /y "%VOXELCUTPATH%\bitmaps\*.png" "%HEEKSCNCPATH%\bitmaps"
